### ISSUE TITLE
Does libspconv support SparseInverseConv3d？

### ISSUE THREAD

**Issue by CreepingBird** [NVIDIA-AI-IOT/Lidar_AI_Solution#100]

**Comment by CreepingBird** [comment]
Hello, may I ask if there is any support for SparseInverseConv3d. I look forward to your reply.

**Comment by lix19937** [comment]
I think, libspconv.so just map to `centerpoint.scn.onnx` code implementation.  
You can try it by setting `inverse=1` in SparseConvolution onnx node ATTRIBUTES.

**Comment by hopef** [comment]
Sorry, currently there is no support for SparseInverseConv3d

**Comment by CreepingBird** [comment]
> You can try it by setting `inverse=1` in **SparseConvolution** onnx node ATTRIBUTES and check the result. Maybe not support now.

Thank you for your reply. I still have some questions. What should I do during training, to remove the SparseInverseConv3d?

**Comment by hopef** [comment]
I have no better recommendation to remove it.

**Comment by CreepingBird** [comment]
> I have no better recommendation to remove it.

can F.interpolate be used instead of SparseInverseConv3d in backbone？

**Comment by CreepingBird** [comment]
>

**Comment by qqcx** [comment]
What a pity.
