### ISSUE TITLE
report error when change shape of spconv   

### ISSUE THREAD

**Issue by lix19937** [NVIDIA-AI-IOT/Lidar_AI_Solution#106]
Hi @hopef, I have customized a spconv-based net, the shape see follow img      
all module.precision & output_precision are **fp16**    

`kernel 128 x 16` is not support ? 

```
Assert failed 💀. false in file src/spconv/implicit-gemm.cu:383, message: Can not find any matched kernel 128 x 16
```

![sp](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/38753233/1cf92c76-f8ce-47d8-89c9-ee03c2ff685d)

**Comment by hopef** [comment]
Sorry, 
Currently, we only provide limited support for libspconv.

**Comment by lix19937** [comment]
@hopef  OK, thanks for your reply.
