### ISSUE TITLE
Why choose hist(mse) calib method in sparseconv quant ?

### ISSUE THREAD

**Issue by lix19937** [NVIDIA-AI-IOT/Lidar_AI_Solution#11]
Good work,I find  https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/CUDA-CenterPoint/qat/tools/sparseconv_quantization.py use `mse`, do you try other calib methods ?  Thanks.

**Comment by liuanqi-libra7** [comment]
Of course, MSE is the best calibration method for our experiments.

**Comment by lix19937** [comment]
@liuanqi-libra7  Ok, Thanks
