### ISSUE TITLE
The result of bevfusion int8 inference is incorrect

### ISSUE THREAD

**Issue by Oh-Cest-la-vie** [NVIDIA-AI-IOT/Lidar_AI_Solution#111]
Hello 

When I infence(CUDA) bevfusion Int8, I find a problem in both A4000 and Drive Orin. The result of fp16 is correct, but the inference with Int8 losed most targets.

[fp16]
![bevfusion_fp16](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/79727512/c46764df-0f1c-4317-8caa-4e572d30478a)

[Int8]
![bevfusion_int8](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/79727512/9b8b1546-9d03-470e-8e52-0f9ca072bc95)

I use TensorRT 8.4.1.5 in A4000 and DRIVE OS 6.0.4 TensorRT 8.4.11 in Drive Orin.

**Comment by Oh-Cest-la-vie** [comment]
I use TensorRT 8.5.3 in A4000, the inference result is correct now. But the latest version of TensorRT in Drive Orin is TensorRT 8.4.12, how can I solve this problem? If you have any other advice, besides upgrading the version of TensorRT?

**Comment by lix19937** [comment]
@Oh-Cest-la-vie  you can update DRIVE OS 6.0.6.0, which TensorRT is v8510

**Comment by Oh-Cest-la-vie** [comment]
Got it, thx @lix19937

**Comment by rayxie11** [comment]
Hi @Oh-Cest-la-vie, I am also using Drive Orin platform. I was not able to get the correct result in neither int8 nor fp16. I was wondering if you have solved this issue and perhaps provide me with some advice on how to make it work on Drive Orin. My email address is rayxie11@gmail.com. I'm also fine with leaving messages here. Thank you!
