### ISSUE TITLE
Why here need disable_quant_layer ? 

### ISSUE THREAD

**Issue by lix19937** [NVIDIA-AI-IOT/Lidar_AI_Solution#113]
Why here  https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/CUDA-CenterPoint/qat/tools/centerpoint_qat_pipline.py#L217       need 
```
disable_quant_layer(model)
```
, I think disable or enable, the `ptq.pth are the same`.   @hopef  Thanks.

**Comment by hopef** [comment]
We want to avoid being affected by quant operations during custom tracers.
So we need to disable the quant.

Note: Custom tracers are not required to perform quantization.

**Comment by lix19937** [comment]
@hopef  OK,   Custom tracers is just to export onnx to libspconv engine ?

**Comment by hopef** [comment]
Y
