### ISSUE TITLE
Lidar2Image not providing pixel coordinates

### ISSUE THREAD

**Issue by alre5639** [NVIDIA-AI-IOT/Lidar_AI_Solution#115]
How does one calculate the intended pixel space location of the bounding boxes generated by the network.

In the example data there is a motorcycle located @ 1.4625, 18.9562, -1.40146 in the Lidar frame. To get this to the back camera frame shouldn't it just be simply `pixels = lidar2image@np.array([[1.4625, 18.9562, -1.40146,1]]).T`. However this results in pixels out of the pixel space.

I took a look at the visualize function and the best I can tell is the bounding box is being mapped to image space using this function, but it seems to be completely static.
```
std::vector<nvtype::Float4> lidar2image = {{param_.norm_size / MaxDistance, 0, 0, param_.cx},
                      {0, -param_.norm_size / MaxDistance, 0, param_.cy},
                      {0, 0, 0, 1},
                     {0, 0, 0, 1}};
```

**Comment by hopef** [comment]
```python
pixels_homogeneous = lidar2image@np.array([[1.4625, 18.9562, -1.40146, 1]]).T

# Normalize the homogeneous coordinate system point.
# Need to scale x and y ( reduce z due to perspective projection).
the_image_point  = pixels_homogeneous[:2] / pixels_homogeneous[[2]]

if pixels_homogeneous[2, 0] <= 0:
    print("Ignore this point because it is behind the camera.")
```
