### ISSUE TITLE
Using libspconv.so , but trained model is from a different spconv

### ISSUE THREAD

**Issue by akjt** [NVIDIA-AI-IOT/Lidar_AI_Solution#118]
Hi, 

So I am attempting to use the current libspconv.so, however,my trained model has been using [this spconv](https://github.com/traveller59/spconv/) - while the names are very similar, I am not sure how well this is going to be?

Any comments from the author regarding using the current libspconv.so for inference when the trained model has been using a different spconv library? I assume if the two libraries are based on the same concepts there should not be a problem?

**Comment by hopef** [comment]
You will find two classic spconv([mmdet3d/spconv](https://github.com/mit-han-lab/bevfusion/tree/main/mmdet3d/ops/spconv) and [traveller59/spconv](https://github.com/traveller59/spconv)) implementations used in this repo if you read the readme carefully. I believe this covers the vast majority of cases.
Moreover, they should not be different when the theory is the same.
