### ISSUE TITLE
centerpoint Inference time

### ISSUE THREAD

**Issue by realwenpeng** [NVIDIA-AI-IOT/Lidar_AI_Solution#12]
The official test case shows that inference time/frame is 42ms，but I had test on my own orin device，inference time is 61ms per frame. I want to know is there any detail should be consider to enhance the inference speed.

**Comment by realwenpeng** [comment]
jetpack version is 5.02, tensorrt version is 8.4.1. sudo nvpmodel -m 0 and sudo jetson_clocks don't work.

**Comment by hopef** [comment]
A newer TensorRT version and higher device frequency will obtain better inference performance.

**Comment by realwenpeng** [comment]
thanks
