### ISSUE TITLE
Where do we find libprotobuf.so.17 for x86 and aarch64

### ISSUE THREAD

**Issue by akjt** [NVIDIA-AI-IOT/Lidar_AI_Solution#126]
Hi  , 
I cannot seem to find a compatible libprotobuf.so.17  which is required for libspconv.so? Any guidance please. I tried installing the 23 version and creating a symlinnk to .17 but that still contains a lot of compatibility issues

**Comment by akjt** [comment]
For anyone looking
https://packages.ubuntu.com/focal/amd64/libprotobuf17/download

**Comment by qqcx** [comment]
Hello. Can it support libprotobuf.so.14? libprotobuf.so.14 is commonly used in programming.

**Comment by twobox** [comment]
> For anyone looking https://packages.ubuntu.com/focal/amd64/libprotobuf17/download

think!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
