### ISSUE TITLE
SparseConvolution.cu

### ISSUE THREAD

**Issue by sxfzzz** [NVIDIA-AI-IOT/Lidar_AI_Solution#13]
Thank you very much for your outstanding work. 
I see that the implementation of SparseConvolution on the deployment side gives the .so file and I was wondering if its code（.cu） will be released.

**Comment by MiaoDX** [comment]
Too advanced to show? :rofl:

**Comment by hopef** [comment]
Sorry, we haven't received any word about opening the source code of libspconv.so

**Comment by sxfzzz** [comment]
> Sorry, I haven't received any word about opening the source code of libspconv.so

thanks for your time
