### ISSUE TITLE
why only 5fps on jetson AGX orin？

### ISSUE THREAD

**Issue by leslie27ch** [NVIDIA-AI-IOT/Lidar_AI_Solution#148]
I run the CUDA-BEVFUION on jetson AGX orin，why there is only 5 fps , much less than 25 fps . 
![图片](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/49723499/26e29605-2d6a-4561-8322-ebc72c3bcc95)

this is jetson AGX orin info:
![图片](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/49723499/25aead18-ef82-472a-86e4-74cbff5402b4)

**Comment by hopef** [comment]
I think you should check the power mode of the device.
like "sudo jetson_clocks".
