### ISSUE TITLE
cuOSD cuosd_draw_polyline bgcolor fill issue

### ISSUE THREAD

**Issue by zxpshadow** [NVIDIA-AI-IOT/Lidar_AI_Solution#152]
When the upper left point is lower than the second point, the background filling is abnormal.
Please assist in confirming, thanks!

![1692016528768](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/20833355/799ea776-4acb-4cde-84f9-870bff66f803)

**Comment by byte-deve** [comment]
This has been fixed. Please take a try with latest commit.
