### ISSUE TITLE
get intermediate results from libspconv engine

### ISSUE THREAD

**Issue by Endlessfancy** [NVIDIA-AI-IOT/Lidar_AI_Solution#157]
Thank you for your great work!

Can I get the output layer by layer? As the code seems to load the onnx model from the libspconv engine, can I get intermediate results from it.

**Comment by hopef** [comment]
I've pushed libspconv-1.1.0, which adds the mark_all_output operator to the inference phase.

https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/tree/master/libraries/3DSparseConvolution

**Comment by Endlessfancy** [comment]
Thank you very much for your assistance!
