### ISSUE TITLE
Jetson AGX Xavier infer Error

### ISSUE THREAD

**Issue by AiQuantPro** [NVIDIA-AI-IOT/Lidar_AI_Solution#16]
Lidar_AI_Solution/CUDA-BEVFusion/src/common/tensor.cu(135): error: calling a __device__ function("__half") from a __host__ function("arange_kernel_host") is not allowed

1 error detected in the compilation of "/tmp/tmpxft_00006d55_00000000-4_tensor.cpp4.ii".
CMake Error at bevfusion_core_generated_tensor.cu.o.Release.cmake:280 (message):
  Error generating file
  /work/share/usr/cyy/BEV/Lidar_AI_Solution/CUDA-BEVFusion/build/CMakeFiles/bevfusion_core.dir/src/common/./bevfusion_core_generated_tensor.cu.o

**Comment by QHdsj1** [comment]
jetson agx xavier算力好像是7.2的，要求是8.0以上的
