### ISSUE TITLE
what is spconv::create_engine_builder

### ISSUE THREAD

**Issue by sandeepnmenon** [NVIDIA-AI-IOT/Lidar_AI_Solution#163]
Thank you for open-sourcing the onnx-parser. I wanted to understand how the engine is being built
https://github.com/SandeepMenonKodiak/Lidar_AI_Solution/blob/0cc359148a773976e20c979369f20bb43d276c84/libraries/3DSparseConvolution/src/onnx-parser.cpp#L97
I did not find the definition of this builder.
I am trying to see if I can get a CUDA dump of this engine so that I can directly execute the CUDA code

**Comment by hopef** [comment]
Sorry, this part is a closed source, and we have no plans to open-source it for now. 
Maybe open source it in the near future.

**Comment by sandeepnmenon** [comment]
Thank you for clarifying.
