### ISSUE TITLE
 No module named 'det3d'

### ISSUE THREAD

**Issue by WYYAHYT** [NVIDIA-AI-IOT/Lidar_AI_Solution#176]
I tried to run `python tool/eval_nusc.py --dump`, got errors like this:
```
Traceback (most recent call last):
  File "tool/eval_nusc.py", line 31, in <module>
    from det3d.torchie import Config
ModuleNotFoundError: No module named 'det3d'
```
I guess there must be a directory named "CenterPoint" in CUDA-CenterPoint, But I can't get it, is there any problem of excuting command `git clone --recursive https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution.git`? But CUDA-CenterPoint seems not a submodule? 

And I trid to clone again, all modules in my workspace are:
![image](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/94819873/87e2cfac-ae0f-4865-9bac-9473d3a5f3b1)

Maybe there is a basic cognition about of git that I ignored, really hope someone can help.

**Comment by WYYAHYT** [comment]
Maybe I should clone CenterPoint repo in CUDA-CenterPoint?

**Comment by hopef** [comment]
yes
