### ISSUE TITLE
libspconv.so 4090 (SM_89) 

### ISSUE THREAD

**Issue by lihao0374** [NVIDIA-AI-IOT/Lidar_AI_Solution#199]
i wonder if this libspconv.so supports 4090 (sm_89)?

**Comment by hopef** [comment]
Sorry, it's not currently compiling on sm89. Because its main purpose is to run on ORIN.
But, more sm may be included later.

**Comment by guhuajun** [comment]
@hopef Looking forward to have tiny version for 2080 TI (SM_75).

**Comment by hopef** [comment]
Actually, the main goal of libspconv.so is to run on orin. 
Of course you can also consider spconv based on traveller59/spconv to solve the spconv problem.

**Comment by lihao0374** [comment]
> Sorry, it's not currently compiling on sm89. Because its main purpose is to run on ORIN. But, more sm may be included later.

Okkk. Thanks for your reply.
