### ISSUE TITLE
Inference results issue

### ISSUE THREAD

**Issue by lucianzhong** [NVIDIA-AI-IOT/Lidar_AI_Solution#2]
I have tried my own data with CUDA-BEVFusion and BEVFusion directly without training. The BEVFusion gives good infercence results. But  CUDA-BEVFusion can not detect person,the vehicle detection is good. Any clue for this?
Best regards

**Comment by mchi-zg** [comment]
is it possible to share your input data?

**Comment by lucianzhong** [comment]
Sure. Please give me your e-mail. I am current on a business trip. I will send you input data tomorrow or the day after tomorrow

**Comment by hopef** [comment]
***@***.***
thanks！

------------------ Original ------------------
From: LucianZhong ***@***.***&gt;
Date: Tue,May 23,2023 7:38 AM
To: NVIDIA-AI-IOT/Lidar_AI_Solution ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [NVIDIA-AI-IOT/Lidar_AI_Solution] Inference results issue (Issue #2)





 
Sure. Please give me your e-mail. I am current on a business trip. I will send you input data tomorrow or the day after tomorrow

**Comment by lucianzhong** [comment]
Has sent the data. Please check QQ mail. Thanks a lot

**Comment by hopef** [comment]
According to the data you provided. I found that the lidar and camera do not match. This may be missing a transformation.

**Comment by lucianzhong** [comment]
Thanks a lot for checking my data. I will try to fix the match problem first.
