### ISSUE TITLE
center point onnx file

### ISSUE THREAD

**Issue by blazeCCC** [NVIDIA-AI-IOT/Lidar_AI_Solution#20]
I don‘t find the script to convert pth to onnx file. If I want to use my own weights, what do I have to do? Keep same name and input and out shape like the onnx file that you provide ?

**Comment by hopef** [comment]
It was combined with quantization and put to [here](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/CUDA-CenterPoint/qat/onnx_export/export-scn.py).
