### ISSUE TITLE
What is the model used for head.bbox for CUDA-BEVFusion?

### ISSUE THREAD

**Issue by sun-lingyu** [NVIDIA-AI-IOT/Lidar_AI_Solution#203]
Hi, I wonder what model  is the used for the head.bbox.onnx model. Is it a Centerpoint head (as the original BEVFusion), a DETR head, or something else?

I found nothing in the documentation and the code of CUDA-BEVFusion in this repo.

Thank you very much.

**Comment by hopef** [comment]
I think you need to look at the BEVFusion paper.
head.bbox is a DETR-style head currently.

**Comment by sun-lingyu** [comment]
Thank you. I checked the BEVFusion paper again, and I think it uses a transfusion head, which combines Centerpoint with DETR. Am I right?
