### ISSUE TITLE
The GPU Compute Capability

### ISSUE THREAD

**Issue by ChunyuFeng** [NVIDIA-AI-IOT/Lidar_AI_Solution#213]
There is a limitation in terms of GPU compute capability, specifically ">=sm_80", and several other issues mentioned this restriction. I am curious if the libspconv.so library is solely responsible for this limitation. Additionally, if I only use the RGB branch and avoid utilizing sparse convolution, can I use devices with lower compute capability (like Xavier, sm_72)?

**Comment by hopef** [comment]
Yes, you can. the SM limitation is valid in libspconv.so only, but the RGB branch has no.

**Comment by ChunyuFeng** [comment]
> Yes, you can. the SM limitation is valid in libspconv.so only, but the RGB branch has no.

Thanks! I'll try this!
