### ISSUE TITLE
Does the coordinate system affect the accuracy?

### ISSUE THREAD

**Issue by eugenebak** [NVIDIA-AI-IOT/Lidar_AI_Solution#237]
Hi !

I successfully trained the fusion model with KITTI dataset based on bevfusion repo.
But, result of tensorrt engine is totally wrong!!

When I use the LiDAR only for inference, I've noticed that the output of LiDAR-only model (SCN) is NaN.

I've carefully modified the corresponding parameters (point cloud range, voxel size, etc. in `main.cpp` and `python.cpp`).

I wonder if it's caused by the different coordinate systems between KITTI and nuScenes...
Or is there any reason which could raise this results..?

Thank you in advance!

**Comment by eugenebak** [comment]
@hopef 
Thank you for your response!

But, the coordinate system of KITTI is not just zyx of nuScenes.

If I denote the nuScenes's coordinates system as `xyz`, the KITTI's one is `(-y)xz`.

Can I apply this coordinate system by editing the source code?

**Comment by eugenebak** [comment]
I think that I need to modify some parts where the scn model is converted to ONNX.

I'll try this and I'll appreciate it if you say another part I need to modify

**Comment by Li-Whasaka** [comment]
Hi, Could you share your work with kitti?

**Comment by eugenebak** [comment]
@Li-Whasaka Hi.
I'm sorry, that work cannot be shared because of the security terms of the company.
It was quite hard work to fit this repo for KITTI. If you tried it, feel free to any question or something

**Comment by chfyyds** [comment]
> @Li-Whasaka Hi. I'm sorry, that work cannot be shared because of the security terms of the company. It was quite hard work to fit this repo for KITTI. If you tried it, feel free to any question or something

Hello, do you need to modify any other files besides the data loading and config? I have successfully run bevfusion on kitti, but the val result is almost 0, I don't know where the problem is, can you give me a useful answer. thank you very much！

**Comment by chfyyds** [comment]
@eugenebak 
Hello, do you need to modify any other files besides the data loading and config? I have successfully run bevfusion on kitti, but the val result is almost 0, I don't know where the problem is, can you give me a useful answer. thank you very much！

**Comment by PW812** [comment]
> Hi !
> 
> I successfully trained the fusion model with KITTI dataset based on bevfusion repo. But, result of tensorrt engine is totally wrong!!
> 
> When I use the LiDAR only for inference, I've noticed that the output of LiDAR-only model (SCN) is NaN.
> 
> I've carefully modified the corresponding parameters (point cloud range, voxel size, etc. in `main.cpp` and `python.cpp`).
> 
> I wonder if it's caused by the different coordinate systems between KITTI and nuScenes... Or is there any reason which could raise this results..?
> 
> Thank you in advance!

Hello！
Have you solved this problem? I am facing the same issue. Could you share your approach or method for resolving it?
Thank you in advance!

**Comment by PW812** [comment]
> @eugenebak Hello, do you need to modify any other files besides the data loading and config? I have successfully run bevfusion on kitti, but the val result is almost 0, I don't know where the problem is, can you give me a useful answer. thank you very much！

Hello！
Have you solved this problem? I am facing the same issue. Could you share your approach or method for resolving it?
Thank you in advance!
