### ISSUE TITLE
Could libspconv provide the IOBinding feature like TensorRT?

### ISSUE THREAD

**Issue by ThomasMouse** [NVIDIA-AI-IOT/Lidar_AI_Solution#264]
Hi,
    Thanks for the great work. When I tried to deploy libspconv in a real-time autonomous driving system, I had to constantly copy the sparse network's inference output into a buffer. Could libspconv provide IOBinding feature to make it possible to pass the GPU pointer to the engine and avoid the extra time-consuming copy operation? We would be grateful if there is any progress.

**Comment by hopef** [comment]
This feature has been supported by commit #9a2c8408b720e9fd25ba15ce836a519030178b25.
