### ISSUE TITLE
预测我自己训练的模型

### ISSUE THREAD

**Issue by evil-master** [NVIDIA-AI-IOT/Lidar_AI_Solution#279]
你好，我基于自己的数据集训练了以resnet50的bevfusion，并可视化看了识别效果是正确的，但是转为onnx后识别结果差别非常大，我对比了数据的输入的参数是一致的，对比了输出结果，box的size差距非常大
![image](https://github.com/user-attachments/assets/9384af25-8cb8-45ed-b21d-634f2bb7c7cf)

此外有点差别的是我在将pth转成PTQ文件时，有报出一些错误：
![image](https://github.com/user-attachments/assets/30028455-a471-4507-a9aa-c62808915be9)

并且camera部分需要改成opset=11才能正常输出onnx文件：
![image](https://github.com/user-attachments/assets/f7122571-1f62-45e8-b06f-8302eff2d7ab)

请问一下，差距是由于模型转换过程中造成的吗，我该怎么去处理它呢？下面是我的识别结果，框s看上去太奇怪了：
![image](https://github.com/user-attachments/assets/33549a1c-2270-4386-91ee-6ab0a3fc43a8)

**Comment by evil-master** [comment]
> 你好，我基于自己的数据集训练了以resnet50的bevfusion，并可视化看了识别效果是正确的，但是转为onnx后识别结果差别非常大，我对比了数据的输入的参数是一致的，对比了输出结果，box的size差距非常大 ![image](https://private-user-images.githubusercontent.com/57422743/363468031-9384af25-8cb8-45ed-b21d-634f2bb7c7cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQyNzksIm5iZiI6MTcyNTMzMzk3OSwicGF0aCI6Ii81NzQyMjc0My8zNjM0NjgwMzEtOTM4NGFmMjUtOGNiOC00NWVkLWIyMWQtNjM0ZjJiYjdjN2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMWVmNGMxOTEwZDYzNDdhMmQ1M2E4YjE0YmQ0MDk2ODIyY2E4ZTdlNjEwOTY0NmI2ZGQwZWYzNjA5ZTA4ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xVzhwovbP5I_nChTsiuGdoCOKq3fe5nmOI4ZBrzWF0I)
> 
> 此外有点差别的是我在将pth转成PTQ文件时，有报出一些错误： ![image](https://private-user-images.githubusercontent.com/57422743/363468332-30028455-a471-4507-a9aa-c62808915be9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQyNzksIm5iZiI6MTcyNTMzMzk3OSwicGF0aCI6Ii81NzQyMjc0My8zNjM0NjgzMzItMzAwMjg0NTUtYTQ3MS00NTA3LWE5YWEtYzYyODA4OTE1YmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjM2NiOTk5M2E0ZDdmN2M2ZWZjODVhMjEwNjc0ZjRjODZhNGU0OWViNjBmN2U4ODdmNjlhYzM1NTk3OThjYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fyi49xxU3lOAHfABAbI0KW_-As_iUucPCxmJ9GJvcFg)
> 
> 并且camera部分需要改成opset=11才能正常输出onnx文件： ![image](https://private-user-images.githubusercontent.com/57422743/363468521-f7122571-1f62-45e8-b06f-8302eff2d7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQyNzksIm5iZiI6MTcyNTMzMzk3OSwicGF0aCI6Ii81NzQyMjc0My8zNjM0Njg1MjEtZjcxMjI1NzEtMWY2Mi00NWU4LWIwNmYtODMwMmVmZjJkN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMTQ2N2QxN2VkOTA3NDk1OWNlY2Q4ZmMxYTg5NDFhN2EwNmY3MmU5ODAyZmQ5OGEyY2JmMDcyZDBmNzc4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dRhCJl6wvn6slEQIg63XJQhlz5Vp6ckiEmGzpoPAoHY)
> 
> 请问一下，差距是由于模型转换过程中造成的吗，我该怎么去处理它呢？下面是我的识别结果，框s看上去太奇怪了： ![image](https://private-user-images.githubusercontent.com/57422743/363468917-33549a1c-2270-4386-91ee-6ab0a3fc43a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQyNzksIm5iZiI6MTcyNTMzMzk3OSwicGF0aCI6Ii81NzQyMjc0My8zNjM0Njg5MTctMzM1NDlhMWMtMjI3MC00Mzg2LTkxZWUtNmFiMGEzZmM0M2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYWFkNTFkOGIyMGU3ZDZkNDlmNmU1NDM4NTQyYmU2NjUzMTA2NTJmMmQzOGNjNGJhZjMwMDM2YTVmZmEwNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OQuoBAnLWLQn-m0z7gqohlurwQQuME2tpvbZ26N60sk)

我这边已经发现问题的原因；问题出现在量化过程，我这边使用nuscenes数据集和配置文件对我的权重PTQ量化后识别正常

**Comment by Anmidy** [comment]
> 你好，我基于自己的数据集训练了以resnet50的bevfusion，并可视化看了识别效果是正确的，但是转为onnx后识别结果差别非常大，我对比了数据的输入的参数是一致的，对比了输出结果，box的size差距非常大 ![image](https://private-user-images.githubusercontent.com/57422743/363468031-9384af25-8cb8-45ed-b21d-634f2bb7c7cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTYwNjQsIm5iZiI6MTczNDMxNTc2NCwicGF0aCI6Ii81NzQyMjc0My8zNjM0NjgwMzEtOTM4NGFmMjUtOGNiOC00NWVkLWIyMWQtNjM0ZjJiYjdjN2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMjI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYTRiOWU0Njk3YTdiODFmNWQ5Y2VhN2UwZjVjYzI2YzIzMzBkZmMyYzRlOWIyNzg3OTljMmRiNjUwMzZlODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GjDfRw1nYThMXPqhRhI3Zcx6cdJu9ws4Q4bRkBS9zfE)
> 
> 此外有点差别的是我在将pth转成PTQ文件时，有报出一些错误： ![image](https://private-user-images.githubusercontent.com/57422743/363468332-30028455-a471-4507-a9aa-c62808915be9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTYwNjQsIm5iZiI6MTczNDMxNTc2NCwicGF0aCI6Ii81NzQyMjc0My8zNjM0NjgzMzItMzAwMjg0NTUtYTQ3MS00NTA3LWE5YWEtYzYyODA4OTE1YmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMjI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NmZiNDAwODExMGZkYTdlYjI2MzNhODJkNDNhODZlZDQ4OGQ3N2FiNWZiYzg3YzkyMmQ3MTRiZDkwNGRiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5BuLHcIPq0UT17X64nWuO6_-SccGYV9r4LJOlcYq4oU)
> 
> 并且camera部分需要改成opset=11才能正常输出onnx文件： ![image](https://private-user-images.githubusercontent.com/57422743/363468521-f7122571-1f62-45e8-b06f-8302eff2d7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTYwNjQsIm5iZiI6MTczNDMxNTc2NCwicGF0aCI6Ii81NzQyMjc0My8zNjM0Njg1MjEtZjcxMjI1NzEtMWY2Mi00NWU4LWIwNmYtODMwMmVmZjJkN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMjI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmODZkNWZkZTYxNDE3N2ZmODQyODY5YWE4ZDI4M2VjNGRiYWEwYmMyYTc5YjYzNGRiZTJmOTI2YmUxMDExNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cSlXqQHvMGSAXnPQ0WGS27DxQ88UUVSr3SyNZ364Gns)
> 
> 请问一下，差距是由于模型转换过程中造成的吗，我该怎么去处理它呢？下面是我的识别结果，框s看上去太奇怪了： ![image](https://private-user-images.githubusercontent.com/57422743/363468917-33549a1c-2270-4386-91ee-6ab0a3fc43a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTYwNjQsIm5iZiI6MTczNDMxNTc2NCwicGF0aCI6Ii81NzQyMjc0My8zNjM0Njg5MTctMzM1NDlhMWMtMjI3MC00Mzg2LTkxZWUtNmFiMGEzZmM0M2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMjI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZmIxNWRhZDk4OTdjMjg2Nzc1MDY0MzJiYzBmNDRhNDZiYTU5N2QzN2VhMGU5ZTIyNGVlZWNjM2EyZTBiN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pHXIreWRo9lCZMkBdlTokzpqlhV8ljXU-wpXu0fXweI)

你好，请问训练resnet50为backbone用的工程是mit版本的代码还是用cuda-bevfusion中的工程代码？配置文件用的那个？我用mit版本的代码和cuda-bevfusion中的configs，训练出来的bevfusion-det 用 ptq.py 量化是报错，KeyError: "NuScenesDataset: 'LoadRadarPointsMultiSweeps is not in the pipeline registry'"

**Comment by ZFcvYes** [comment]
> > 你好，我基于自己的数据集训练了以resnet50的bevfusion，并可视化看了识别效果是正确的，但是转为onnx后识别结果差别非常大，我对比了数据的输入的参数是一致的，对比了输出结果，box的size差距非常大 ![image](https://private-user-images.githubusercontent.com/57422743/363468031-9384af25-8cb8-45ed-b21d-634f2bb7c7cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTYwNjQsIm5iZiI6MTczNDMxNTc2NCwicGF0aCI6Ii81NzQyMjc0My8zNjM0NjgwMzEtOTM4NGFmMjUtOGNiOC00NWVkLWIyMWQtNjM0ZjJiYjdjN2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMjI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYTRiOWU0Njk3YTdiODFmNWQ5Y2VhN2UwZjVjYzI2YzIzMzBkZmMyYzRlOWIyNzg3OTljMmRiNjUwMzZlODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GjDfRw1nYThMXPqhRhI3Zcx6cdJu9ws4Q4bRkBS9zfE)
> > 此外有点差别的是我在将pth转成PTQ文件时，有报出一些错误： ![image](https://private-user-images.githubusercontent.com/57422743/363468332-30028455-a471-4507-a9aa-c62808915be9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTYwNjQsIm5iZiI6MTczNDMxNTc2NCwicGF0aCI6Ii81NzQyMjc0My8zNjM0NjgzMzItMzAwMjg0NTUtYTQ3MS00NTA3LWE5YWEtYzYyODA4OTE1YmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMjI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NmZiNDAwODExMGZkYTdlYjI2MzNhODJkNDNhODZlZDQ4OGQ3N2FiNWZiYzg3YzkyMmQ3MTRiZDkwNGRiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5BuLHcIPq0UT17X64nWuO6_-SccGYV9r4LJOlcYq4oU)
> > 并且camera部分需要改成opset=11才能正常输出onnx文件： ![image](https://private-user-images.githubusercontent.com/57422743/363468521-f7122571-1f62-45e8-b06f-8302eff2d7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTYwNjQsIm5iZiI6MTczNDMxNTc2NCwicGF0aCI6Ii81NzQyMjc0My8zNjM0Njg1MjEtZjcxMjI1NzEtMWY2Mi00NWU4LWIwNmYtODMwMmVmZjJkN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMjI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmODZkNWZkZTYxNDE3N2ZmODQyODY5YWE4ZDI4M2VjNGRiYWEwYmMyYTc5YjYzNGRiZTJmOTI2YmUxMDExNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cSlXqQHvMGSAXnPQ0WGS27DxQ88UUVSr3SyNZ364Gns)
> > 请问一下，差距是由于模型转换过程中造成的吗，我该怎么去处理它呢？下面是我的识别结果，框s看上去太奇怪了： ![image](https://private-user-images.githubusercontent.com/57422743/363468917-33549a1c-2270-4386-91ee-6ab0a3fc43a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTYwNjQsIm5iZiI6MTczNDMxNTc2NCwicGF0aCI6Ii81NzQyMjc0My8zNjM0Njg5MTctMzM1NDlhMWMtMjI3MC00Mzg2LTkxZWUtNmFiMGEzZmM0M2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAyMjI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZmIxNWRhZDk4OTdjMjg2Nzc1MDY0MzJiYzBmNDRhNDZiYTU5N2QzN2VhMGU5ZTIyNGVlZWNjM2EyZTBiN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pHXIreWRo9lCZMkBdlTokzpqlhV8ljXU-wpXu0fXweI)
> 
> 你好，请问训练resnet50为backbone用的工程是mit版本的代码还是用cuda-bevfusion中的工程代码？配置文件用的那个？我用mit版本的代码和cuda-bevfusion中的configs，训练出来的bevfusion-det 用 ptq.py 量化是报错，KeyError: "NuScenesDataset: 'LoadRadarPointsMultiSweeps is not in the pipeline registry'"

请问您head.bbox.onnx转成engine可以成功吗？我使用官方提供的model/resnet50int8/bevfusion_ptq.pth权重，使用export-transfuser.py转成onnx后，与官方提供的不一致，且无法使用build_trt_engine.sh转成功。

**Comment by ZFcvYes** [comment]
> > 你好，我基于自己的数据集训练了以resnet50的bevfusion，并可视化看了识别效果是正确的，但是转为onnx后识别结果差别非常大，我对比了数据的输入的参数是一致的，对比了输出结果，box的size差距非常大 ![image](https://private-user-images.githubusercontent.com/57422743/363468031-9384af25-8cb8-45ed-b21d-634f2bb7c7cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQyNzksIm5iZiI6MTcyNTMzMzk3OSwicGF0aCI6Ii81NzQyMjc0My8zNjM0NjgwMzEtOTM4NGFmMjUtOGNiOC00NWVkLWIyMWQtNjM0ZjJiYjdjN2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMWVmNGMxOTEwZDYzNDdhMmQ1M2E4YjE0YmQ0MDk2ODIyY2E4ZTdlNjEwOTY0NmI2ZGQwZWYzNjA5ZTA4ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xVzhwovbP5I_nChTsiuGdoCOKq3fe5nmOI4ZBrzWF0I)
> > 此外有点差别的是我在将pth转成PTQ文件时，有报出一些错误： ![image](https://private-user-images.githubusercontent.com/57422743/363468332-30028455-a471-4507-a9aa-c62808915be9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQyNzksIm5iZiI6MTcyNTMzMzk3OSwicGF0aCI6Ii81NzQyMjc0My8zNjM0NjgzMzItMzAwMjg0NTUtYTQ3MS00NTA3LWE5YWEtYzYyODA4OTE1YmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjM2NiOTk5M2E0ZDdmN2M2ZWZjODVhMjEwNjc0ZjRjODZhNGU0OWViNjBmN2U4ODdmNjlhYzM1NTk3OThjYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fyi49xxU3lOAHfABAbI0KW_-As_iUucPCxmJ9GJvcFg)
> > 并且camera部分需要改成opset=11才能正常输出onnx文件： ![image](https://private-user-images.githubusercontent.com/57422743/363468521-f7122571-1f62-45e8-b06f-8302eff2d7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQyNzksIm5iZiI6MTcyNTMzMzk3OSwicGF0aCI6Ii81NzQyMjc0My8zNjM0Njg1MjEtZjcxMjI1NzEtMWY2Mi00NWU4LWIwNmYtODMwMmVmZjJkN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMTQ2N2QxN2VkOTA3NDk1OWNlY2Q4ZmMxYTg5NDFhN2EwNmY3MmU5ODAyZmQ5OGEyY2JmMDcyZDBmNzc4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dRhCJl6wvn6slEQIg63XJQhlz5Vp6ckiEmGzpoPAoHY)
> > 请问一下，差距是由于模型转换过程中造成的吗，我该怎么去处理它呢？下面是我的识别结果，框s看上去太奇怪了： ![image](https://private-user-images.githubusercontent.com/57422743/363468917-33549a1c-2270-4386-91ee-6ab0a3fc43a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQyNzksIm5iZiI6MTcyNTMzMzk3OSwicGF0aCI6Ii81NzQyMjc0My8zNjM0Njg5MTctMzM1NDlhMWMtMjI3MC00Mzg2LTkxZWUtNmFiMGEzZmM0M2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYWFkNTFkOGIyMGU3ZDZkNDlmNmU1NDM4NTQyYmU2NjUzMTA2NTJmMmQzOGNjNGJhZjMwMDM2YTVmZmEwNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OQuoBAnLWLQn-m0z7gqohlurwQQuME2tpvbZ26N60sk)
> 
> 我这边已经发现问题的原因；问题出现在量化过程，我这边使用nuscenes数据集和配置文件对我的权重PTQ量化后识别正常

请问您head.bbox.onnx转成engine可以成功吗？我使用官方提供的model/resnet50int8/bevfusion_ptq.pth权重，使用export-transfuser.py转成onnx后，与官方提供的不一致，且无法使用build_trt_engine.sh转成功。
