### ISSUE TITLE
which ORIN chip for fps numbers?

### ISSUE THREAD

**Issue by kurquhar** [NVIDIA-AI-IOT/Lidar_AI_Solution#280]
Per the ORIN spec sheet (https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-orin/) there are seven different ORIN devices with an order of magnitude difference in TOPS.  Exactly which ORIN device was used for the published fps numbers (e.g. 18FPS @ FP16 on ORIN)?

**Comment by hopef** [comment]
ORIN-X 64GB with max power.
