### ISSUE TITLE
./tool/run.sh: 行 41: 22500 段错误               (核心已转储) ./build/bevfusion $DEBUG_DATA $DEBUG_MODEL $DEBUG_PRECISION

### ISSUE THREAD

**Issue by QHdsj1** [NVIDIA-AI-IOT/Lidar_AI_Solution#29]
大佬能麻烦帮我看一下问题出现在哪里吗？还是这是我的显卡不支持吗？
ubuntu18.04
RTX3080ti

![2023-05-23 16-06-22 的屏幕截图](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/73505323/9686f240-e224-4522-9a60-5453c29c3d2c)
![2023-05-23 16-07-22 的屏幕截图](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/73505323/cc87e9f5-bf74-4d07-a7b5-b3a424553a01)

**Comment by hopef** [comment]
可以考虑运行gdb排查build/bevfusion，看看错误发生在哪一行。
看起来设备时能够支持的，可能是环境的配置存在问题。
