### ISSUE TITLE
Why conv.weight.permute(4, 0, 1, 2, 3)  in fuse_bn function of CUDA-BEVFusion/qat/lean/funcs.py?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [NVIDIA-AI-IOT/Lidar_AI_Solution#294]
There is no permute in https://github.com/traveller59/spconv/blob/master/example/fuse_bn_act.py.

**Comment by hopef** [comment]
The repository you mentioned doesn't have a permutation for weights, and so?

**Comment by Icecream-blue-sky** [comment]
> The repository you mentioned doesn't have a permutation for weights, and so?

In CUDA-BEVFusion/qat/lean/funcs.py line 79:
![image](https://github.com/user-attachments/assets/4a9003c7-99e8-46ae-a4d2-98d876d3be15)

However, I already know the reason. https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/issues/205
