### ISSUE TITLE
What is the Jetpack version on Orin to run BEVFusion?

### ISSUE THREAD

**Issue by dpan817** [NVIDIA-AI-IOT/Lidar_AI_Solution#3]
What is the Jetpack version on Orin to run BEVFusion? 5.1.0, or the latest 5.1.1?

**Comment by mchi-zg** [comment]
Recommend the latest release - Jetpack 5.1.1 with TensorRT 8.5.2 , newer is better.
https://developer.nvidia.com/embedded/jetpack-sdk-511
