### ISSUE TITLE
core dumped by CUDA Runtime error spconv::setup_hash_and_route

### ISSUE THREAD

**Issue by leslie27ch** [NVIDIA-AI-IOT/Lidar_AI_Solution#30]
(base) qiu@qiu-System-Product-Name:~/Lidar_AI_Solution/CUDA-BEVFusion$ bash tool/run.sh
==========================================================
||  MODEL: resnet50
||  PRECISION: fp16
||  DATA: example-data
||  USEPython: OFF
||
||  TensorRT: /usr/local/TensorRT-8.5.1.7/lib
||  CUDA: /usr/local/cuda
||  CUDNN: /usr/local//cuda/lib64
==========================================================
Try to get the current device SM
Current CUDA SM: 75
Configuration done!
-- Configuring done
-- Generating done
-- Build files have been written to: /home/qiu/Lidar_AI_Solution/CUDA-BEVFusion/build
[ 63%] Built target bevfusion_core
[100%] Built target bevfusion
Create by resnet50, fp16
------------------------------------------------------
Camerea Backbone 🌱 is Static Shape model
Inputs: 2
	0.img : {1 x 6 x 3 x 256 x 704} [Float16]
	1.depth : {1 x 6 x 1 x 256 x 704} [Float16]
Outputs: 2
	0.camera_depth_weights : {6 x 118 x 32 x 88} [Float16]
	1.camera_feature : {6 x 32 x 88 x 80} [Float16]
------------------------------------------------------
------------------------------------------------------
Camerea VTransform 🌱 is Static Shape model
Inputs: 1
	0.feat_in : {1 x 80 x 360 x 360} [Float16]
Outputs: 1
	0.feat_out : {1 x 80 x 180 x 180} [Float16]
------------------------------------------------------
------------------------------------------------------
Transfusion 🌱 is Static Shape model
Inputs: 2
	0.camera : {1 x 80 x 180 x 180} [Float16]
	1.lidar : {1 x 256 x 180 x 180} [Float16]
Outputs: 1
	0.middle : {1 x 512 x 180 x 180} [Float16]
------------------------------------------------------
------------------------------------------------------
BBox 🌱 is Static Shape model
Inputs: 1
	0.middle : {1 x 512 x 180 x 180} [Float16]
Outputs: 6
	0.reg : {1 x 2 x 200} [Float16]
	1.height : {1 x 1 x 200} [Float16]
	2.dim : {1 x 3 x 200} [Float16]
	3.rot : {1 x 2 x 200} [Float16]
	4.vel : {1 x 2 x 200} [Float16]
	5.score : {1 x 10 x 200} [Float16]
------------------------------------------------------
==================BEVFusion===================
[⏰ [NoSt] CopyLidar]: 	1.13885 ms
[⏰ [NoSt] ImageNrom]: 	12.50054 ms

CUDA Runtime error spconv::setup_hash_and_route<<<(num_input + 1023) / 1024, 1024, 0, stream>>>( hash_.get(), route_mask_.ptr(), route_.ptr(), indices, num_input, prob.kv) # no kernel image is available for execution on the device, code = cudaErrorNoKernelImageForDevice [ 209 ] in file src/spconv/rulebook.cu:138
tool/run.sh: line 41: 28104 Aborted                 (core dumped) ./build/bevfusion $DEBUG_DATA $DEBUG_MODEL $DEBUG_PRECISION

thanks for reply

**Comment by hopef** [comment]
libspconv requires sm80 or higher, but your device is 75.
