### ISSUE TITLE
When kernel_size = (1,1,1) for SparseConv3d, the onnx inference result is different from the torch

### ISSUE THREAD

**Issue by Icecream-blue-sky** [NVIDIA-AI-IOT/Lidar_AI_Solution#302]
I change the last sparse conv of bevfusion from the first picture to the second (I don't want to downsample):
![image](https://github.com/user-attachments/assets/cb43a52d-823a-4d86-aa01-aa73e20b5633)

![image](https://github.com/user-attachments/assets/46fa9ed5-157f-4aa3-986d-16b7751fdc40)

It will cause the final lidar feat to be incorrect. The onnx inference result is inaccurate while the torch inference is normal. I think this is probably a bug...

**Comment by hopef** [comment]
Please clean the argument "indice_key" because the rulebook needs to be recomputed.

**Comment by Icecream-blue-sky** [comment]
> Please clean the argument "indice_key" because the rulebook needs to be recomputed.

This has nothing to do with indice_key. I tried or set indice_key="", indice_key="spconv_4", indice_key="spconv_down2", all do not work. However, after using 1*1*3 conv, I succeeded.

**Comment by hopef** [comment]
Could you share a minimal reproduced code with me?

**Comment by Icecream-blue-sky** [comment]
> Could you share a minimal reproduced code with me?

Unfortunately, I cannot provide it, because I use BEVFusion from mmdetection3d and have customized it, and I have solved the problem. I just hope that others can try my solution when they encounter similar problems.

**Comment by Muxindawang** [comment]
> > Could you share a minimal reproduced code with me?你能分享一个最小化的可复现代码给我吗？
> 
> Unfortunately, I cannot provide it, because I use BEVFusion from mmdetection3d and have customized it, and I have solved the problem. I just hope that others can try my solution when they encounter similar problems.不幸的是，我不能提供它，因为我使用的是 mmdetection3d 的 BEVFusion，并且进行了定制，我已经解决了这个问题。我只是希望当其他人遇到类似问题时能尝试我的解决方案。

hello did you have solved this question, I meet the same question? use conv 1*1 rather than upsample, and onnx result is mistake, pytorch is right.
