### ISSUE TITLE
/home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/src/main.cpp:30:10: fatal error: stb_image.h: 没有那个文件或目录    30 | #include <stb_image.h>       |          ^~~~~~~~~~~~~ compilation terminated.

### ISSUE THREAD

**Issue by xqh5201314** [NVIDIA-AI-IOT/Lidar_AI_Solution#31]
你好，报这个错如何解决
/home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/src/main.cpp:30:10: fatal error: stb_image.h: 没有那个文件或目录
   30 | #include <stb_image.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

**Comment by lzh1998-jansen** [comment]
请问这个解决了吗，怎么解决的？

**Comment by xqh5201314** [comment]
报这个错是github下载的文件不完全，重新下载就可以了
