### ISSUE TITLE
你好，请问报这个错如何解决

### ISSUE THREAD

**Issue by xqh5201314** [NVIDIA-AI-IOT/Lidar_AI_Solution#32]
/usr/bin/ld: warning: libprotobuf.so.17, needed by /home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: undefined reference to `google::protobuf::internal::RegisterAllTypes(google::protobuf::Metadata const*, int)'
/usr/bin/ld: /home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32SlowPath(unsigned int)'
/usr/bin/ld: /home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint64SlowPath(unsigned long)'
/usr/bin/ld: /home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: undefined reference to `google::protobuf::internal::WireFormat::SerializeUnknownFields(google::protobuf::UnknownFieldSet const&, google::protobuf::io::CodedOutputStream*)'
/usr/bin/ld: /home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAligned(unsigned long)'
/usr/bin/ld: /home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: undefined reference to `google::protobuf::internal::AssignDescriptors(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
/usr/bin/ld: /home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: undefined reference to `google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(google::protobuf::UnknownFieldSet const&, unsigned char*)'
/usr/bin/ld: /home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: undefined reference to `google::protobuf::Message::ParseFromIstream(std::istream*)'
/usr/bin/ld: /home/chenyang/Lidar_AI_Solution_3/CUDA-BEVFusion/../libraries/3DSparseConvolution/libspconv/lib/x86_64/libspconv.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/bevfusion.dir/build.make:678：bevfusion] 错误 1
make[1]: *** [CMakeFiles/Makefile2:111：CMakeFiles/bevfusion.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2

**Comment by hopef** [comment]
你需要安装libprotobuf-dev == 3.6.1
通过sudo apt install libprotobuf-dev==3.6.1
