### ISSUE TITLE
执行bash tool/run.sh报错

### ISSUE THREAD

**Issue by HZQNPU** [NVIDIA-AI-IOT/Lidar_AI_Solution#39]
在执行bash tool/run.sh的时候报错，请问该怎么解决？
fatal error: stb_image.h: 没有那个文件或目录
 #include <stb_image.h>
          ^~~~~~~~~~~~~
compilation terminated.
CMakeFiles/bevfusion.dir/build.make:504: recipe for target 'CMakeFiles/bevfusion.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/bevfusion.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/bevfusion.dir/all' failed
make[1]: *** [CMakeFiles/bevfusion.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hopef** [comment]
You must follow the steps described in the readme.
1. sudo apt-get install git-lfs
2. git clone --recursive https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution

This repo has a lot of dependencies that will be handled by the --recursive and git-lfs.

**Comment by HZQNPU** [comment]
好的 非常感谢

**Comment by leijr** [comment]
为什么我按照这个操作进行完：
sudo apt-get install git-lfs
git clone --recursive https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution
还是一样的出现这个错误？

**Comment by leijr** [comment]
大家出现这个问题的，记得多试几次。。。我试了两次好了
