### ISSUE TITLE
plugin for SparseConvolution

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA-AI-IOT/Lidar_AI_Solution#4]
Hi:
I can see that there is custom onnx node "SparseConvolution" in Centerpoint middle encoder onnx file. However, I can't find its plugin or how this onnx is converted to tensorrt engine. Can you guide me to where to find it?

**Comment by hopef** [comment]
It is not a plugin. Because the data-depend characteristic can not be supported in the current version of TensorRT. So we implemented a tiny engine in a standalone way.

**Comment by hopef** [comment]
So it only needs to build the execution graph from the ONNX file, which doesn't need to convert to a TensorRT engine.

**Comment by shuyuan-wang** [comment]
Got it, so the spconv part won't be converted to an tensorrt engine?

**Comment by shuyuan-wang** [comment]
Got it

**Comment by shuyuan-wang** [comment]
Any plan on adding inverse sparse convolution?

**Comment by hopef** [comment]
This support will be in the queue.
