### ISSUE TITLE
Can other networks that use Spconv, such as VoxelRCNN, also use NV spconv scn for TensorRT acceleration？

### ISSUE THREAD

**Issue by wayyeah** [NVIDIA-AI-IOT/Lidar_AI_Solution#40]
Can other networks that use Spconv, such as VoxelRCNN, also use NV spconv scn for TensorRT acceleration？
其他使用了Spconv的网络例如VoxelRCNN同样能够使用NV spconv-scn进行TensorRT加速吗？

**Comment by hopef** [comment]
Yes, you can. It is building the execution graph by ONNX. So you need to refer to the ONNX export script provided [here](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/CUDA-BEVFusion/qat/export-scn.py), and then You can use it anywhere.

**Comment by wayyeah** [comment]
> Yes, you can. It is building the execution graph by ONNX. So you need to refer to the ONNX export script provided [here](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/CUDA-BEVFusion/qat/export-scn.py), and then You can use it anywhere.

Thanks for your answer!!
