### ISSUE TITLE
support of custom dataset

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA-AI-IOT/Lidar_AI_Solution#43]
Hi:
Does your sparse convolution support inference with input shape N*4? When I'm trying to inference, it says 

![image](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/104115572/3e43638c-7fa9-45d1-915c-8a82d0145575)

**Comment by hopef** [comment]
Sorry, the libspconv currently only supports nx5 input. We will add further support as needed and release it in the future.

**Comment by shuyuan-wang** [comment]
Does spatial shape  have any limit?

**Comment by hopef** [comment]
There are no limitations. It just requires more effort.

**Comment by wangxu5** [comment]
Can you please update libsponv.so to be able to support the N*3 input？Thanks~ @hopef

**Comment by hopef** [comment]
Ok, I will add it

**Comment by qiaxigua** [comment]
Can you please update libsponv.so to be able to support the N*6 input？Thanks~

**Comment by qiaxigua** [comment]
Can you please update libspconv.so to be able to support the N*3 input？Thanks~ @hopef

**Comment by qiaxigua** [comment]
Can you please update libspconv.so to be able to support the N*6 input？Thanks~ @hopef
