### ISSUE TITLE
在运行CUDA-BEVFusion的时候遇到这个错误，fatal error: stb_image.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by lzh1998-jansen** [NVIDIA-AI-IOT/Lidar_AI_Solution#45]
![image](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/61367424/3c57a72b-9502-4fdd-8009-d8c30667b794)

**Comment by hopef** [comment]
Same as #39
