### ISSUE TITLE
how to train model/resnet50int8/bevfusion_ptq.pth ?

### ISSUE THREAD

**Issue by hzm8341** [NVIDIA-AI-IOT/Lidar_AI_Solution#48]
I have train the code in bevfuion[@ db75150] ,using resnet50 config ,but when I export my pth to onnx, that is wrong.

**Comment by hopef** [comment]
You can refer to the case we provided for ONNX export. If there is an error, please comment it here. Thanks

**Comment by hzm8341** [comment]
you provided example pth file is goog to export onnx，but I want to use my trained pth file.
could you provid the train code or configs ?

**Comment by hopef** [comment]
We did not change anything in the training code, and you can follow the steps in the readme to get your ONNX.

**Comment by hzm8341** [comment]
OK,thanks,I will try again.

**Comment by OrangeJuice3211** [comment]
> OK,thanks,I will try again.

hello，did you solve this problem？ I want to use my trained pth file to export onnx，but there is no model in the pth file,there is state_dict only.

**Comment by OrangeJuice3211** [comment]
> > OK,thanks,I will try again.
> 
> hello，did you solve this problem？ I want to use my trained pth file to export onnx，but there is no model in the pth file,there is state_dict only.

and the pth file is got from bevfusion train code.
