### ISSUE TITLE
Question about customized dataset

### ISSUE THREAD

**Issue by jianingwangind** [NVIDIA-AI-IOT/Lidar_AI_Solution#5]
Hi, thanks for sharing the great work and congrats to the achievements!

I have a question regarding to customized dataset: 

This repo is mainly designed to implement the model inference highly effeciently, so if i want to follow your work, the first thing to do is to trainng customized dataset with the official BEVFusion repo within Pytorch, right?

**Comment by hopef** [comment]
Yes, you need to do your work on [BEVFusion-PyTorch](https://github.com/mit-han-lab/bevfusion).
