### ISSUE TITLE
Can not find any matched kernel 4 x 16

### ISSUE THREAD

**Issue by blazeCCC** [NVIDIA-AI-IOT/Lidar_AI_Solution#52]
Hello， i have converted my centerpoint model to onnx. I only use 4 feature as input while use 5 in your code, then the error occurs.
```
Pass argument constructor
Assert failed 💀. false in file src/spconv/implicit-gemm.cu:346, message: Can not find any matched kernel 4 x 16

```
Is it my bug in my code or the project don't support other input shape?

**Comment by hopef** [comment]
same as #43
