### ISSUE TITLE
CenterPoint different inference result compared with Readme.md

### ISSUE THREAD

**Issue by bigsheep2018** [NVIDIA-AI-IOT/Lidar_AI_Solution#53]
Hello Lidar_AI_Solution Team @hopef ,

Following the instructions mentioned in [Readme.md](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/CUDA-CenterPoint/README.md), I can get the results as follows

![result0](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/45345643/e2f8fbac-7d9b-4c36-9d75-8781b43572d6)

**we can see the Detection NUM is different from the official result mentioned in Readme.md as follows**

![result1](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/45345643/0adfae2e-069d-404a-a29b-c0101f27a7c0)

**For further checking the difference, I visualize the results in rviz and find more false positive detection from my results**
**Official performance in Readme.md:**
![result3](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/45345643/3e6c7df3-ec55-46e6-a100-996422c50758)

**My visualization (ignore construction_vehicle, barriers, trailer, traffic_cone):**
![result4](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/45345643/31b66e12-9db9-435a-9e9e-dc3658779eb0)

**May I know why this situation happen? is it normal (maybe caused by hardware difference or different post-processing code)? and is there any solution to solve it?**

**Comment by hopef** [comment]
Sorry, the data in the readme is legacy. 
We fixed bugs in the code, but we didn't update the readme in time.

**Comment by bigsheep2018** [comment]
thanks @hopef . closing the issue.
