### ISSUE TITLE
export onnx

### ISSUE THREAD

**Issue by areyouok12** [NVIDIA-AI-IOT/Lidar_AI_Solution#54]
你好，我们只使用一个相机和一个雷达，请问我应该在哪修改代码，才能使Camerea Backbone的dim变为1 x 1 x 1 x 256 x 704，谢谢。

**Comment by hopef** [comment]
你需要直接在bevfusion的训练代码中去调整，这个工作不属于这里的讨论范畴。你需要对bevfusion pytorch本身具有一定了解。
