### ISSUE TITLE
centerpoint rpn+head int8

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA-AI-IOT/Lidar_AI_Solution#55]
Hi, how do you do rpn+head int8 for centerpoint model? do you use pytorch_quantization or tensorrt's native int8?

**Comment by fengguibinyn** [comment]
hi,bro,read more readme

**Comment by shuyuan-wang** [comment]
> hi,bro,read more readme

I can see that in the readme, there is mention of int8 on RPN+head:
![Screenshot from 2023-05-31 19-29-08](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/104115572/0555011d-f76a-42d2-80de-8b33ddf3382d)

However, when reading the building script, There is only mention of fp16:
![Screenshot from 2023-05-31 19-34-19](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/104115572/fe79f8b4-fd01-4bc2-8e41-d578f9dfa692)

If I use pytorch_quantization to add explicit quantization on the rpn+head part, I can't seem to get the engine to run as fast as mentioned on readme. That's why I'm asking this question. Not sure where this part is mentioned. Is it in CUDA-BevFusion?
