### ISSUE TITLE
How to determine the location of the tensorrt file

### ISSUE THREAD

**Issue by chenzb0712** [NVIDIA-AI-IOT/Lidar_AI_Solution#57]
Hello, I would like to ask about "modify the TensorRT/CUDA/CUDNN/BEVFusion variable value in the tool/environment.sh file." How to determine the location of the tensorrt file in this step, I use jeston orin32, jetpack version 5.1

**Comment by hopef** [comment]
Typically on jetson, the TensorRT directory is defined as follows: 
TensorRT_Inc    /usr/include/aarch64-linux-gnu/
TensorRT_Lib    /lib/aarch64-linux-gnu
TensorRT_Bin   /usr/src/tensorrt/bin/

CUDA_Inc    /usr/local/cuda/include
CUDA_Bin   /usr/local/cuda/bin
CUDA_Lib   /usr/local/cuda/lib64
CUDA_HOME    /usr/local/cuda

CUDNN_Lib    /usr/lib/aarch64-linux-gnu/
