### ISSUE TITLE
Generate more example data

### ISSUE THREAD

**Issue by andyluo7** [NVIDIA-AI-IOT/Lidar_AI_Solution#59]
How to generate data like this from NuScenes?
![image](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/43718156/bbbbbd42-bc72-442a-9193-b380bbe85b0a)

**Comment by hopef** [comment]
This [file](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/CUDA-BEVFusion/tool/dump-data.py) may be helpful to you.
