### ISSUE TITLE
SparseConvolution version

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA-AI-IOT/Lidar_AI_Solution#6]
What is the spconv version used in this repo?

**Comment by hopef** [comment]
This repo will be dependent on CenterPoint/BEVFusion's own spconv environment for onnx exports. 
It comes from [traveller59/spconv](https://github.com/traveller59/spconv) and [mmdet3d/spconv](https://github.com/mit-han-lab/bevfusion/tree/main/mmdet3d/ops/spconv).
You can find more details in [this readme](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/README.md#cuda-bevfusion).
For deployment of this model, it will only depend on the Cuda and TensorRT.
