### ISSUE TITLE
Support for semantic segmentation, such as cyclinder 3D, minkunet, etc.?

### ISSUE THREAD

**Issue by CreepingBird** [NVIDIA-AI-IOT/Lidar_AI_Solution#63]
Hello, may I ask if there is any support for semantic segmentation, such as cyclinder 3D, minkunet, etc. I look forward to your reply.

**Comment by hopef** [comment]
Our work showed that the semantic segmentation head on BEVFusion could be easily integrated into this repo.
Currently, only object detection is provided.

Based on demand, we will consider adding support for `cyclinder 3D`, `minkunet`, etc..
