### ISSUE TITLE
The dataset of PTQ

### ISSUE THREAD

**Issue by Oh-Cest-la-vie** [NVIDIA-AI-IOT/Lidar_AI_Solution#65]
Hello

I have another question. I see the code in calibrate_model, you select the first 400 frames to calibration(if we set calibrate_batch=400). I wonder if you simply used the first hundred frames or you've picked several typical keyframes? When I simply used first 400 frames to PTQ, the result is not good enough.

thx

**Comment by hopef** [comment]
For the `nuscenes` dataset, 400 data are distinguished. For your dataset, you should use 400 keyframes instead of consecutive frames.
