### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by chenzb0712** [NVIDIA-AI-IOT/Lidar_AI_Solution#68]
Hello, I ran the code on orin according to the operation on github, but the running time is not as fast as you said, is there something wrong with my settings?
![Screenshot from 2023-06-01 09-35-37](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/131951950/582edffc-e43c-44a4-b614-6a60c8a11aad)

**Comment by hopef** [comment]
There are large fluctuations in elapsed time, as indicated by your print message. You need to confirm that the device is working at a stable maximum performance mode.

**Comment by dav695** [comment]
Hello, 
In my case i have the same problem. My Total inference time is around 190 ms. I am using the device Jetson Orin developer Kit. I do not understand what i have to do to test this part:  "You need to confirm that the device is working at a stable maximum performance mode".
Thanks you so much!
