### ISSUE TITLE
NUM_TASKS

### ISSUE THREAD

**Issue by Rex-LK** [NVIDIA-AI-IOT/Lidar_AI_Solution#72]
hello,What does NUM_TASKS mean？

**Comment by byte-deve** [comment]
Hi, are you referring to https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/22441d130651c4a3a6dc071b0c34ec4d43c905bf/CUDA-CenterPoint/include/common.h#L42?
It's task header number from center-point detection config.

**Comment by Rex-LK** [comment]
thankyou
