### ISSUE TITLE
3D Sparse Convolution Network not support kernel 4 x 16?

### ISSUE THREAD

**Issue by KingJamesYF** [NVIDIA-AI-IOT/Lidar_AI_Solution#73]
Assert failed 💀. false in file src/spconv/implicit-gemm.cu:346, message: Can not find any matched kernel 4 x 16
![gAAvqeym3i](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/32009339/3c7be605-7373-4eaf-9d93-19dfe6c229b8)

**Comment by KingJamesYF** [comment]
![nMCVz0aWv5](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/32009339/1930d7bf-6144-48ef-911d-afc38b842e34)

**Comment by hopef** [comment]
Currently, only nx5 input is supported. We will provide support for nx4 input as soon as possible. Please refer here #43

**Comment by KingJamesYF** [comment]
thanks for your time

**Comment by hopef** [comment]
Now you can update `libspconv.so` to be able to support the Nx4 input.

**Comment by KingJamesYF** [comment]
> Now you can update `libspconv.so` to be able to support the Nx4 input.

Thanks a lot
