### ISSUE TITLE
libspconv.so relationship to the traveller59 / spconv

### ISSUE THREAD

**Issue by HuangVictorAuto** [NVIDIA-AI-IOT/Lidar_AI_Solution#75]
Hello,

thanks for the great work. could you give us the hint, what's the relationship between the libspconv.so used in this project and that one in traveller59/spconv here?

https://github.com/traveller59/spconv/tree/master/example/libspconv

Thanks!

**Comment by hopef** [comment]
`traveller59/spconv` is an excellent library for sparse convolution training practice.

We have evaluated integrating his work. But it is too heavy for reasoning on different platforms like `ORIN/Drive/QNX/Safety`. To handle these problems and use `libspconv` better, we did not even depend on `cutlass`.

This is the story of how we developed `libspconv.so`.

Thanks!

**Comment by YoushaaMurhij** [comment]
@hopef, Could you please provide libspconv.so for cu12?
