### ISSUE TITLE
libspconv support for non-centerpoint model

### ISSUE THREAD

**Issue by superpigforever** [NVIDIA-AI-IOT/Lidar_AI_Solution#77]
Hi:
does libspconv.so support any model with sparse/subm conv ops or does it only support centerpoint/Bevfusion for now?

**Comment by hopef** [comment]
As it is the execution graph constructed by `onnx`. So you just need to meet the [basic requirements](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/tree/master/libraries/3DSparseConvolution#note) to get support. And don't care if it's centerpoint/bevfusion or not.

**Comment by hopef** [comment]
For CenterPoint and BEVFusion. They are only examples of our practice that you can benefit from.

**Comment by superpigforever** [comment]
Thanks
