### ISSUE TITLE
Precision of  SparseConvolution

### ISSUE THREAD

**Issue by Oh-Cest-la-vie** [NVIDIA-AI-IOT/Lidar_AI_Solution#8]
Hello,

I see in you PTQ.onnx file and export-scn.py, your precisions of the first three SparseConvolution are 'fp16', is this because there is too much loss of accuracy with precision 'int8' ?

Thanks

**Comment by liuanqi-libra7** [comment]
Yes, in this example, if the first few sparseconvolution layers use int8 precision, it will lead to significant degradation in accuracy.
