### ISSUE TITLE
关于doPostNMSCuda

### ISSUE THREAD

**Issue by yumendecc** [NVIDIA-AI-IOT/Lidar_AI_Solution#81]
你好，我尝试将doPostNMSCuda方法移植到我的项目中，但是发现doPostNMSCuda方法执行完后偶尔仍然存在一些重叠的3d box，我想知道这种情况是正常的吗？点文件目标有200个左右，nms阈值设置为0.001，而且我注意到出现重叠框的情况通常两个3d box [的执行度差别较大，比如0.42，0.21。这是否有可能是doPostNMSCuda方法并没有对多个block之间的数据进行nms处理导致？

**Comment by ryanyej** [comment]
same question here.  any solution?
