### ISSUE TITLE
The indice from scn engine is incorrect

### ISSUE THREAD

**Issue by Junx0924** [NVIDIA-AI-IOT/Lidar_AI_Solution#82]
Hi,
Thanks for this fantastic work.

I find the indices [(pyscn.cpp)](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/blob/master/libraries/3DSparseConvolution/src/pyscn.cpp) are not correctly extracted from scn engine.

numel is the size of the out_indice, however it is 1.
ndim is the dimension of the out_indice, it is 0.
Can you help to solve this issue?

![Screenshot from 2023-06-09 15-59-08](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/18465543/e8d09be9-af8a-4608-95dd-362f36d65142)

**Comment by hopef** [comment]
For the SCN model, the last layer converts the sparse tensor to dense. 
therefore it will only have feature(out_feature), but no indices(out_indices). So the result I observed here is correct.

**Comment by Junx0924** [comment]
So this is the result of the current scn onnx model.

Can you show a way to add indices as an output to the onnx model?

**Comment by hopef** [comment]
You will get indices if you remove the `ScatterToDense` node in the scn model.

**Comment by Junx0924** [comment]
Thanks, after modifying the scn onnx model, now it looks correct!

![Screenshot from 2023-06-12 12-50-59](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/18465543/9e4d10ee-1f74-4215-946f-5f52a1857555)
![Screenshot from 2023-06-12 12-52-02](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/18465543/622eb716-4514-4364-8555-697964611b83)
