### ISSUE TITLE
 scn_engine_->forward error

### ISSUE THREAD

**Issue by lishanxiuxiu** [NVIDIA-AI-IOT/Lidar_AI_Solution#84]
我的输入是nx4，所以我的scn_engine输入也是nx4.然而在执行到centerpoint.cpp时，scn_engine_->forward会报错：CUDA Runtime error spconv::setup_hash_and_route<<<(num_input + 1023) / 1024, 1024, 0, stream>>>( hash_.get(), route_mask_.ptr(), route_.ptr(), indices, num_input, prob.kv) # no kernel image is available for execution on the device, code = cudaErrorNoKernelImageForDevice [ 209 ] in file src/spconv/rulebook.cu:150
请问，我怎么解决这个问题？

**Comment by hopef** [comment]
Please use a device with sm>=80
