### ISSUE TITLE
FPS does not reach the predicted value

### ISSUE THREAD

**Issue by pocky111** [NVIDIA-AI-IOT/Lidar_AI_Solution#87]
Hello, I tried to run the bev fusion model on orin. My environment configuration is Jetpack5.0.2, CUDA11.4.2, cuDNN8.4.1.50 and Tensorrt8.4.1.5. However, I got the following results after running the demo with the Resnet50PTQ model, the FPS value basically remained around 12-15, and my physical computer was in the highest power consumption mode. Can you give me some advice on this problem? thank you

![20230613-135243](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/100056759/50000ba0-f0f6-49ad-92f5-9683771b8ebf)

**Comment by hopef** [comment]
Your device seems to be unstable. Consider running it for a long time to see if it stabilizes.

**Comment by pocky111** [comment]
Okay thanks,i' ll try it and see how it works.
