### ISSUE TITLE
CUDA-CenterPoint INT8 inference performance

### ISSUE THREAD

**Issue by liuxingwt** [NVIDIA-AI-IOT/Lidar_AI_Solution#92]
![image](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/assets/90546778/e9b8c321-7a9f-46dd-92dc-40ab53cb7ee6)

Hello, 
  Thanks for your excellent job.
  In the CUDA-CenterPoint README file, time consume of each component in CenterPoint is shown with FP16 precision. What about time consume of INT8 precision? especially for 3D backbone.

**Comment by hopef** [comment]
you can find it [here](https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/tree/master/libraries/3DSparseConvolution#performance-on-orin).

**Comment by liuxingwt** [comment]
Got it! Thanks for your reply.
