### ISSUE TITLE
How to use libspconv in plugin?

### ISSUE THREAD

**Issue by HuapengXu** [NVIDIA-AI-IOT/Lidar_AI_Solution#95]
How could I use the libspconv.so in deploying? 

If there were a demo showing how to use the lib in deploying, It would be great.

Anyway, if the lib can be used in tensorrt, the spconv operators should be packaged as a plugin, is it?

**Comment by hopef** [comment]
You should refer `cuda-bevfusion/cuda-centerpoint`. they are best practices for using librspconv.so.
